stages:
  - triggers
  - cd

ci:
  stage: triggers
  trigger:
    include: .gitlab-ci/ci.yml
    strategy: depend

cd:
  stage: cd
  trigger:
    include: .gitlab-ci/cd.yml
    strategy: depend
  needs: [ci]
