stages:
  - triggers
  - cd

ci:
  stage: triggers
  trigger:
    include: .gitlab-ci/ci.yml

mirror:
  stage: triggers
  trigger:
    include: .gitlab-ci/mirror.yml

cd:
  stage: cd
  trigger:
    include: .gitlab-ci/cd.yml
