stages:
  - build
  - deploy

variables:
  TAG_LATEST: $CI_COMMIT_REF_NAME:latest

build:
  image: docker:latest
  stage: build
  variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2
  services:
   - docker:18.09-dind
  script:
    - docker build -t $TAG_LATEST .
    - docker save -o ./$TAG_LATEST.tar $TAG_LATEST
  artifacts:
    paths:
    - $TAG_LATEST.tar

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - scp -i $ID_RSA -o StrictHostKeyChecking=no ./$TAG_LATEST.tar $SERVER_USER@$SERVER_IP:~/$TAG_LATEST.tar
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f fyp || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker load -i ~/$TAG_LATEST.tar"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 80:8080 --name fyp $TAG_LATEST"
  environment:
    name: production
    url: http://$SERVER_IP
  only:
    - master
