image: node:16.16.0

before_script:
  - cd ./backend
  - yarn install --cache-folder .yarn

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - test

unit-test-job:
  stage: test
  script:
    - yarn dap-client
    - yarn test

lint-test-job:
  stage: test
  script:
    - yarn lint

format-test-job:
  stage: test
  script:
    - yarn format:check
