stages:
  - push

push-job:
  stage: push
  script:
    - git clone --bare "https://oauth2:$PERSONAL_TOKEN@gitlab.com/jxn819/fyp-testing.git"
    - cd fyp-testing.git
    - git push --mirror "https://oauth2:$MIRROR_TOKEN@git.cs.bham.ac.uk/projects-2022-23/jxn819.git"
